baseURL = "https://jorgee97.github.io/"
languageCode = "en-us"
title = "Jorge Gomez"
theme = "beautifulhugo"

[Params]
    subtitle = "Software developer looking to live a pythonic way"
    logo = "img/avatar.jpg"
    rss = true
    comments = true
    readingTime = true
    wordCount = true
    showRelatedPosts = true


[Author]
    name = "Jorge Gomez"
    github = "jorgee97"
    email = "ingjorgegomez@outlook.com"
    twitter = "androidciudadan"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3